version: '3'
services:

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=nvasyankin@list.ru
      - PGADMIN_DEFAULT_PASSWORD=${DB_PASS} 
    ports:
      - '8080:80'
    depends_on:
      - db